name = "recipeboy-api"
main = "worker.js"
compatibility_date = "2026-08-31"

[vars]
CLERK_ISSUER = "https://clerk.bensonperry.com"
CLERK_AUTHORIZED_PARTIES = "https://bensonperry.com,http://127.0.0.1:4173,http://localhost:4173"

[[d1_databases]]
binding = "DB"
database_name = "recipeboy-db"
database_id = "fa2de50f-6ad7-4133-b4ea-c9f9c41b0b6b"

[[ratelimits]]
name = "CREATE_RATE_LIMITER"
namespace_id = "726931001"

  [ratelimits.simple]
  limit = 5
  period = 60

[[ratelimits]]
name = "DELETE_RATE_LIMITER"
namespace_id = "726931002"

  [ratelimits.simple]
  limit = 10
  period = 60

[[ratelimits]]
name = "MADE_RATE_LIMITER"
namespace_id = "726931003"

  [ratelimits.simple]
  limit = 30
  period = 60
